[caprover]
prefix = "caprover-backup-"
suffix = ".tar"
filename = "caprover.tar"

[strava]
prefix = "export_"
suffix = ".zip"
filename = "strava.zip"
filename_length = 19

[github]
prefix = ""
suffix = ".tar.gz"
filename = "github.tar.gz"
filename_length = 43