[caprover]
prefix = "caprover-backup-"
suffix = ".tar"
filename = "caprover.tar"

[strava]
prefix = "export_"
suffix = ".zip"
length = 19
filename = "strava.zip"

[github]
prefix = ""
suffix = ".tar.gz"
length = 43
filename = "github.tar.gz"