name: format

on:
  - push
  - pull_request
  - release

jobs:
  beautysh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - uses: snok/install-poetry@v1.1.1
      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-root -n
      - name: beautysh update.sh
        run: |
          beautysh update.sh
          git diff --exit-code
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-root -n
      - run: autopep8 --aggressive --exit-code --recursive --diff .
